#!/usr/bin/env sh
# Standalone niri setup — window manager config + keybinds, nothing else.
# Same script works alone: clone the repo, run this, get a working niri.
set -eu

DIR="$(cd "$(dirname "$0")" && pwd)"
CONF="$HOME/.config/niri"

command -v niri >/dev/null 2>&1 || echo "WARNING: niri not found on PATH — config will just sit there until it's installed"

mkdir -p "$CONF"

link() {
  src="$1"
  dst="$2"
  if [ -L "$dst" ]; then
    rm "$dst"
  elif [ -e "$dst" ]; then
    mv "$dst" "$dst.bak"
  fi
  ln -s "$src" "$dst"
}

link "$DIR/config.kdl" "$CONF/config.kdl"
link "$DIR/binds.kdl"  "$CONF/binds.kdl"

# noctalia.kdl is regenerated by noctalia's theme engine on every theme
# change, so it's never symlinked — that would fight the live app. Seed it
# once so config.kdl's `include "noctalia.kdl"` doesn't fail niri's very
# first start (before noctalia has run and written its own copy).
[ -e "$CONF/noctalia.kdl" ] || cp "$DIR/noctalia.kdl" "$CONF/noctalia.kdl"

echo "niri config ready. Reload: niri msg action load-config-file (or re-login)."
